"""Build the offline kanji lesson data.

python scripts/build_kanji.py path/to/kanjivg.zip path/to/kanjidic2.xml.gz
Requires Python only. Source spellings are reviewed against sources/new-words.pdf.
KANJIDIC2: EDRDG, CC BY-SA 4.0. KanjiVG: Ulrich Apel, CC BY-SA 3.0.
See sources/kanji/README.md for provenance and the review procedure.
"""
import gzip
import hashlib
import json
import re
import sys
import unicodedata
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if len(sys.argv) != 3:
    raise SystemExit(__doc__)
vgpath, kdpath = map(Path, sys.argv[1:])
vocab = json.loads((ROOT/'data/vocabulary.js').read_text(encoding='utf-8').split('const RAW_VOCAB = ')[1].strip().removesuffix(';'))
sources = json.loads((ROOT/'data/kanji-source.json').read_text(encoding='utf-8'))
expected = [i for i,w in enumerate(vocab) if re.search('[一-龥]',w['k']) and not w.get('example')]
assert [s['index'] for s in sources] == expected, 'Review PDF source mappings after changing vocabulary.'
for s in sources:
    w = vocab[s['index']]
    assert (s['word'], s['lesson'], s['topic'], s['page']) == (w['k'], w['l'], w['t'], w['p']), s
chars = sorted(set(''.join(re.findall('[一-龥]', ''.join(vocab[i]['k'] for i in expected)))))
notes = {}
for line in (ROOT/'data/kanji-meanings.tsv').read_text(encoding='utf-8').splitlines():
    if not line or line.startswith('#'): continue
    char,hv,meaning=line.split('|')
    assert char not in notes, char
    notes[char]={'hv': hv.split('/') if hv != '—' else [], 'meaning':meaning}
assert set(notes) == set(chars), ('Missing',set(chars)-set(notes),'Extra',set(notes)-set(chars))
dictionary=ET.fromstring(gzip.decompress(kdpath.read_bytes()))
kd={entry.findtext('literal'):entry for entry in dictionary.findall('character')}
vg=zipfile.ZipFile(vgpath)
prefix=vg.namelist()[0]
ns={'svg':'http://www.w3.org/2000/svg'}
data={}
def attr(el,key):
    return next((value for name,value in el.attrib.items() if name.endswith('}'+key)), '')
for char in chars:
    entry=kd[char]
    svg=ET.fromstring(vg.read(f'{prefix}kanji/{ord(char):05x}.svg'))
    paths=svg.findall('.//svg:path',ns)
    assert paths and all(p.get('d') for p in paths), char
    main=next(g for g in svg.findall('.//svg:g',ns) if attr(g,'element')==char)
    parts=[{'element':attr(g,'element'),'position':attr(g,'position')} for g in main.findall('svg:g',ns) if attr(g,'element')]
    labels=[]
    for t in svg.findall('.//svg:text',ns):
        values=re.findall(r'-?\d+(?:\.\d+)?',t.get('transform',''))
        assert len(values)==6, (char,values)
        labels.append([float(v) for v in values])
    assert len(labels)==len(paths), char
    counts=[int(e.text) for e in entry.findall('misc/stroke_count')]
    assert len(paths) in counts, (char,len(paths),counts)
    data[char]={**notes[char],
        'on':[x.text for x in entry.findall('.//reading[@r_type="ja_on"]')],
        'kun':[x.text for x in entry.findall('.//reading[@r_type="ja_kun"]')],
        'parts':parts,
        'strokes':[p.get('d') for p in paths], 'numbers':labels}
meta={'kanjivg':prefix.rstrip('/').removeprefix('kanjivg-'),
      'kanjidicDate':dictionary.findtext('header/date_of_creation'),
      'kanjidicSHA256':hashlib.sha256(kdpath.read_bytes()).hexdigest(),
      'kanjivgSHA256':hashlib.sha256(vgpath.read_bytes()).hexdigest(),
      'wordCount':len(sources),'characterCount':len(data)}
output='// Generated by scripts/build_kanji.py. KANJIDIC2 (EDRDG), KanjiVG (Ulrich Apel).\n// Derived data licensed CC BY-SA 4.0; see sources/kanji/README.md.\n'
for name,value in [('KANJI_META',meta),('KANJI_SOURCES',sources),('KANJI_CHARACTERS',data)]:
    output+=f'const {name} = '+json.dumps(value,ensure_ascii=False,separators=(',',':'))+';\n'
(ROOT/'data/kanji.js').write_text(output,encoding='utf-8')
print(json.dumps(meta,ensure_ascii=False))
